2.1.0
- Fixed Inventory updating in 1.20.1
> Error: "Can't place player in the world" on Join.
- Fixed give command's context error.
- Switched to Spindle (Config Management Library)
> https://github.com/Furq07/Spindle